import type { Metadata } from "next";
import { Logo } from "@/components/Logo";

export const metadata: Metadata = {
  title: "Privacy Policy — Skriptly",
  description: "What Skriptly stores, for how long, who processes it, and how to delete it.",
};

export default function PrivacyPage() {
  return (
    <div className="legal-page">
      <header className="legal-header">
        <a href="/" aria-label="Back to Skriptly home"><Logo /></a>
        <a href="/" className="legal-back">← Back to home</a>
      </header>

      <main className="legal-content">
        <span className="eyebrow">Legal</span>
        <h1 className="display xxl">Privacy Policy</h1>
        <p className="legal-date">Last updated: September 2026</p>

        <section>
          <h2>1. Overview</h2>
          <p>Skriptly (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) is a transcription service for calls and uploaded audio, with a Windows app for dictation. This policy explains what data we process, why, how long we keep it, who processes it for us, and what rights you have. We don&apos;t sell your data and we don&apos;t use it to train AI models.</p>
        </section>

        <section>
          <h2>2. Audio</h2>
          <p><strong>Recordings and uploads.</strong> Audio you record in the web app or the Windows app, or upload as a file, is sent to our speech recognition provider (Soniox) to produce the transcript. We delete the file at Soniox as soon as the transcript is returned.</p>
          <p><strong>Our copy.</strong> We keep a copy of each recording or upload in our own storage (Cloudflare R2) for <strong>90 days</strong>, together with technical diagnostics of the recording (audio levels, silent channels, microphone switches, browser and operating system). We use it only to investigate transcription errors and improve quality; only the founder has access. After 90 days it is deleted automatically. Deleting your account deletes it immediately; to delete a single recording sooner, write to us (section 9).</p>
          <p><strong>Dictation.</strong> In the Windows app, dictation audio is streamed directly to Soniox for live recognition and is not stored by us. If &quot;Polish with AI&quot; is on, the recognized text is sent to Google Gemini to remove filler words; we don&apos;t store it.</p>
          <p>Your audio is never used to train AI models — neither ours nor our providers&apos;.</p>
        </section>

        <section>
          <h2>3. Transcripts and AI features</h2>
          <p>Transcripts are stored in our database (Supabase) so you can access your history on any device. They are private by default — only you can see them unless you share them through a workspace. You can edit or delete any transcript at any time; deletion is permanent.</p>
          <p>To improve accuracy, the transcript text is sent to Google Gemini for correction. Summaries and action items are generated by OpenAI (with Google Gemini as a fallback). Only text is sent to these providers, never audio. Terms the AI corrects repeatedly are saved to your personal vocabulary, which you can edit in Settings.</p>
        </section>

        <section>
          <h2>4. Account data</h2>
          <p>We store your email address, subscription plan, usage (call minutes and dictation time), preferences and your vocabulary. We do not collect payment card data — purchases are sold and processed by Link (Stripe) as the merchant of record.</p>
        </section>

        <section>
          <h2>5. Analytics and session recordings</h2>
          <p>We use PostHog (EU instance) for product analytics: which features are used, errors, and session recordings of the app. <strong>Session recordings capture what is shown on screen in the app, including transcript text</strong>; password fields are masked. We use them only to find and fix bugs, and they are deleted automatically after PostHog&apos;s retention period. If you object to session recordings of your account, write to us and we will exclude it.</p>
        </section>

        <section>
          <h2>6. Who processes data for us</h2>
          <ul>
            <li><strong>Soniox</strong> — speech recognition (audio).</li>
            <li><strong>Google (Gemini API)</strong> — transcript correction, dictation clean-up, summary fallback (text).</li>
            <li><strong>OpenAI</strong> — summaries and action items (text).</li>
            <li><strong>Modal Labs</strong> — our backend servers (US).</li>
            <li><strong>Supabase</strong> — sign-in and database.</li>
            <li><strong>Cloudflare R2</strong> — 90-day copy of recordings (section 2).</li>
            <li><strong>PostHog</strong> — analytics and session recordings (EU).</li>
            <li><strong>Vercel</strong> — website hosting.</li>
            <li><strong>Stripe / Link</strong> — merchant of record for purchases: payment, receipts, sales tax and VAT.</li>
            <li><strong>Notion</strong> — only if you connect it, to send transcripts there.</li>
            <li><strong>Telegram</strong> — internal notifications to the founder about new sign-ups and subscriptions (includes your email).</li>
          </ul>
          <p>Some of these providers are located outside the EU; transfers rely on their standard contractual clauses.</p>
        </section>

        <section>
          <h2>7. Security</h2>
          <p>All data in transit uses TLS. Data at rest is encrypted by our storage providers. Row-Level Security ensures you can only access your own data, and every request is authenticated.</p>
        </section>

        <section>
          <h2>8. Your rights</h2>
          <p>Under GDPR you have the right to access, correct, export and delete your data, and to object to processing. Delete your account from <strong>Settings → Danger zone</strong> — this removes your transcripts, profile and our copies of your recordings. Export transcripts as Markdown at any time. For anything else, write to us.</p>
        </section>

        <section>
          <h2>9. Contact</h2>
          <p>Privacy questions and requests: <a href="mailto:privacy@skriptly.io">privacy@skriptly.io</a></p>
        </section>
      </main>

      <footer className="legal-footer">
        <span>© 2026 Skriptly</span>
        <a href="/terms">Terms of Service</a>
        <a href="/">Back to home</a>
      </footer>
    </div>
  );
}
